import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../components/self/theme-provider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import QueryProvider from "./queryprovider";


export const metadata: Metadata = {
  title: "PostPearl",
  description: "Generated by Vishwas",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
        <GoogleOAuthProvider clientId="455624080761-2e7vh29o5qldeimm6qn96qaqjhhgk85h.apps.googleusercontent.com">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            
        {children}
        <ReactQueryDevtools></ReactQueryDevtools>
        </ThemeProvider>
        </GoogleOAuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
